### ISSUE TITLE
jsdoc fails with `Unable to parse... Unexpected token get`

### ISSUE THREAD

**Issue by RasPhilCo** [heroku/http-call#6]
Appears jsdoc3 (from jsdoc2md) isn't parsing ES5 getters `get`

Whenever addressed, be sure to add the version script below back:
```
"version": "npm run doc && git add README.md",
```

**Comment by ransombriggs** [comment]
@RasPhilCo I also get this error too and it prevents cutting a new version (I cut a new one by hand)
